/**
 * Human-first display names for runtime records.
 *
 * Rule (user-locked): record identity is publisher + family + official ID
 * ("NIST AC 3.1.1"). The publisher's record name is supporting text, never a
 * generated summary. Internal scaffold ids (FAMILY-AC, DOC-STRATEGY, HIGH)
 * never become record titles on their own.
 */

import { displayNameFor } from "../../app/display-names.mjs";
import { nistFamilyCode } from "../../shared/nist-families.mjs";
import { controlContextLabel } from "../../shared/record-control-context.mjs";
import { sourceNativeIdentityCategory } from "../../shared/record-identity.mjs";


export type TitledNode = {
  id: string;
  node_type?: string;
  label?: string;
  metadata?: {
    item_id?: string;
    publisher_item_id?: string;
    title?: string;
    catalog_id?: string;
    family?: string;
    identity_category?: string;
  };
};

/** Family-qualify otherwise ambiguous NIST requirement numbers. */
export function familyQualifiedRecordId(
  itemId: string,
  family?: string,
  catalogId?: string,
): string {
  const identifier = itemId.trim();
  if (!/^\d+(?:\.\d+)+$/.test(identifier)) return identifier;
  if (
    !["nist-800-171", "nist-800-171-rev2", "nist-800-172"].includes(
      catalogId || "",
    )
  ) {
    return identifier;
  }
  const familyCode = nistFamilyCode(family);
  return familyCode ? `${familyCode}-${identifier}` : identifier;
}

/** Return only a publisher-authored record name; never turn body text into a title. */
export function officialRecordName(itemId: string, title: string): string {
  const identifier = itemId.trim();
  const publishedTitle = title.trim();
  if (!publishedTitle || publishedTitle.toLocaleLowerCase() === identifier.toLocaleLowerCase()) {
    return "";
  }
  const escapedIdentifier = identifier.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return publishedTitle
    .replace(new RegExp(`^${escapedIdentifier}(?:\\s*[-–—:|]\\s*|\\s+)`, "i"), "")
    .trim();
}

function familyIdentity(family: string): string {
  const label = family.trim();
  return nistFamilyCode(label) || label;
}

const GENERIC_PUBLISHER_LABELS = new Set([
  "other",
  "publisher unavailable",
  "source owner",
  "unavailable",
]);

/** Prefer an actual organization name over generic catalog buckets. */
export function recordPublisherName(...values: unknown[]): string {
  for (const value of values) {
    const label = String(value || "").trim();
    if (!label || GENERIC_PUBLISHER_LABELS.has(label.toLocaleLowerCase())) continue;
    if (/^National Institute of Standards and Technology\b/i.test(label)) return "NIST";
    if (/^Defense Information Systems Agency\b/i.test(label)) return "DISA";
    if (/^(?:The )?MITRE(?: Corporation)?\b/i.test(label)) return "MITRE";
    return label;
  }
  return "";
}

function identifierIncludesFamily(identifier: string, family: string): boolean {
  if (!identifier || !family) return false;
  const escapedFamily = family.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`(?:^|[-.])${escapedFamily}(?:[-.]|$)`, "i").test(identifier);
}

/**
 * Build the concise identity shown wherever a record is titled.
 *
 * Numeric NIST requirements need their family code ("NIST AC 3.1.1"). IDs
 * that already carry the family stay intact ("NIST AC-2", not
 * "NIST AC AC-2"). Other catalogs keep their published family label.
 */
export function formatRecordIdentity(
  publisher: string,
  family: string,
  itemId: string,
): string {
  const publisherLabel = publisher.trim();
  const identifier = itemId.trim();
  const familyLabel = familyIdentity(family);
  const parts = [publisherLabel];
  if (familyLabel && !identifierIncludesFamily(identifier, familyLabel)) {
    parts.push(familyLabel);
  }
  if (identifier) parts.push(identifier);
  return parts.filter(Boolean).join(" ");
}

export function recordIdentityFor(input: {
  publisher: string;
  catalogId: string;
  itemId: string;
  family: string;
  metadata?: TitledNode["metadata"];
}): string {
  const category = input.metadata?.identity_category || sourceNativeIdentityCategory({
    catalogId: input.catalogId,
    family: input.family,
  });
  return formatRecordIdentity(input.publisher, category, input.itemId);
}

/**
 * Record types whose stable item key is generated by Control Atlas rather
 * than assigned by the publisher. Keep this list explicit: a new adapter must
 * make a deliberate presentation decision instead of inheriting a checksum
 * heading through a naming heuristic.
 */
export const GENERATED_STABLE_ID_TYPES: ReadonlySet<string> = new Set([
  "zt_collaborator",
  "zt_mapping_contributor",
  "zt_mapping_document",
  "zt_product_component",
  "zt_reference_component",
  "iot_capability_domain",
  "iot_capability",
  "iot_subcapability",
  "iot_capability_element",
  "iot_capability_subelement",
  "mobile_threat_category",
]);

/**
 * Node types whose stable key is a Control Atlas scaffold ("CATEGORY-PR.AA",
 * "BENCHMARK-VMW-...", "FAMILY-AC") rather than a publisher designation. The
 * publisher's own title is the human identity for these records; the scaffold
 * key stays routable and copyable but never leads a heading, breadcrumb, or
 * browser title.
 */
export const SCAFFOLD_STABLE_ID_TYPES: ReadonlySet<string> = new Set([
  "baseline",
  "benchmark",
  "catalog",
  "category",
  "family",
  "function",
  "group",
  "impact_category",
  "policy",
  "program",
  "rmf_step",
  "tactic",
  "zt_document",
  "zt_pillar",
  "zt_tenet",
]);

/**
 * `requirement` covers catalogs with a real short publisher code (NIST AI RMF's
 * "GOVERN 1.1", SSDF's "PO.1.1", 800-171's "3.1.1") and catalogs where the
 * ingestion adapter had to invent a key because the publisher only names the
 * item ("Holistic", "Set Foundations") with no code of its own. DoD's
 * Responsible AI Toolkit is the latter: "PRINCIPLE-ETHICS" and
 * "SHIELD-DETECT" are Control Atlas keys, not DoD identifiers.
 */
const SCAFFOLD_STABLE_ID_CATALOG_TYPES: ReadonlySet<string> = new Set([
  "dod-rai:requirement",
]);

/** True when the record's item_id is a Control Atlas key rather than a published ID. */
export function usesScaffoldStableId(objectType: string, stableId = "", catalogId = ""): boolean {
  if (objectType === "tactic") {
    return !/^TA\d{4}$/i.test(stableId.trim());
  }
  return (
    SCAFFOLD_STABLE_ID_TYPES.has(objectType) ||
    GENERATED_STABLE_ID_TYPES.has(objectType) ||
    SCAFFOLD_STABLE_ID_CATALOG_TYPES.has(`${catalogId}:${objectType}`)
  );
}

export type RecordIdentityPresentation = {
  primary: string;
  secondary: string;
  context: string;
  accessibleName: string;
  browserTitle: string;
  stableId: string;
  stableIdIsGenerated: boolean;
};

/**
 * Separate publisher-native identifiers from Control Atlas routing keys.
 * Native IDs remain identity-led. Generated keys stay stable and copyable,
 * while the publisher-authored title becomes the human-facing identity.
 */
export function recordIdentityPresentationFor(input: {
  publisher: string;
  catalogId: string;
  publicationName?: string;
  family: string;
  itemId: string;
  title: string;
  objectType: string;
  metadata?: TitledNode["metadata"];
}): RecordIdentityPresentation {
  const stableId = input.itemId.trim();
  const stableIdIsGenerated = usesScaffoldStableId(input.objectType, stableId, input.catalogId);
  const publisherItemId = input.metadata?.publisher_item_id?.trim() || "";
  const displayId = publisherItemId || stableId;
  const nativePrimary = recordIdentityFor({ ...input, itemId: displayId });
  const publishedName = officialRecordName(displayId, input.title);

  // FedRAMP publishes control context under its own id (CTL-AC-06-01). Lead with
  // the control practitioners know and keep the publisher's exact title beneath.
  const contextLabel = input.objectType === "control_context" ? controlContextLabel(stableId) : null;
  if (contextLabel) {
    const primary = [input.publisher.trim(), contextLabel, "parameters and guidance"].filter(Boolean).join(" ");
    const official = input.title.trim();
    return {
      primary,
      secondary: official && official !== primary ? official : "",
      context: "",
      accessibleName: primary,
      browserTitle: [primary, official].filter(Boolean).join(" — "),
      stableId,
      stableIdIsGenerated: false,
    };
  }

  if (!stableIdIsGenerated) {
    return {
      primary: nativePrimary,
      secondary: publishedName,
      context: "",
      accessibleName: nativePrimary,
      browserTitle: [nativePrimary, publishedName].filter(Boolean).join(" — "),
      stableId,
      stableIdIsGenerated: false,
    };
  }

  // A scaffold key is not a publisher designation, so it is never stripped from
  // the publisher's title. Baselines are keyed HIGH / LOW / MODERATE and titled
  // "High Impact Baseline"; stripping the key left every baseline as
  // "Impact Baseline".
  const primary = publisherItemId
    ? formatRecordTitle(publisherItemId, input.title)
    : input.title.trim() || stableId;
  const recordType = displayNameFor("object_type", input.objectType);
  const publication = input.publicationName?.trim() || input.catalogId;
  const context = [recordType, publication].filter(Boolean).join(" · ");

  return {
    primary,
    secondary: "",
    context,
    accessibleName: [primary, recordType, publication]
      .filter(Boolean)
      .join(", "),
    browserTitle: [primary, context].filter(Boolean).join(" — "),
    stableId,
    stableIdIsGenerated: true,
  };
}

/** Keep only locators that read as public document citations, never file paths or fragments. */
export function humanReadableEvidenceLocator(locator: string): string {
  const value = locator.trim();
  if (!value || /[#/\\]/.test(value)) return "";
  if (/\b[0-9a-f]{8}-[0-9a-f-]{27,}\b/i.test(value)) return "";
  if (/\.(?:csv|json|pdf|xml|xlsx?)\b/i.test(value)) return "";
  return /^(?:appendix|clause|figure|page|paragraph|row|section|table|§)\b/i.test(value) ||
    /^\d+\s+(?:CFR|U\.S\.C\.)\b/i.test(value)
    ? value
    : "";
}

/**
 * Construct one identifier-led title without repeating an identifier the
 * publisher already placed at the beginning of the official title.
 *
 * The boundary check is intentionally narrow. It removes only a leading,
 * standalone identifier (case-insensitive), while preserving the same token
 * when it appears later in legitimate official text.
 */
export function formatRecordTitle(itemId: string, officialTitle: string): string {
  const identifier = itemId.trim();
  const title = officialTitle.trim();
  if (!identifier) return title;
  if (!title) return identifier;
  if (title.toLocaleLowerCase() === identifier.toLocaleLowerCase()) {
    return identifier;
  }
  const leadingIdentifier = title.slice(0, identifier.length);
  const boundary = title.slice(identifier.length, identifier.length + 1);
  if (
    leadingIdentifier.toLocaleLowerCase() === identifier.toLocaleLowerCase() &&
    (!boundary || boundary === "[" || boundary === "]" || /[-\s\u2013\u2014:|()]/.test(boundary))
  ) {
    return title;
  }
  return `${identifier} — ${title}`;
}

export function recordDisplayTitle(node: TitledNode | null | undefined): string {
  if (!node) return "";
  const itemId = node.metadata?.item_id ?? "";
  const publisherItemId = node.metadata?.publisher_item_id ?? "";
  const title = node.metadata?.title ?? "";
  if (!title) return node.label || itemId || node.id;
  if (publisherItemId) return formatRecordTitle(publisherItemId, title);
  if (!itemId || title === itemId) return title;
  if (node.node_type === "family") {
    const familyCode = itemId.replace(/^FAMILY-/, "");
    return `${title} (${familyCode}) family`;
  }
  if (usesScaffoldStableId(node.node_type ?? "", itemId, node.metadata?.catalog_id ?? "")) {
    return title;
  }
  return formatRecordTitle(itemId, title);
}
